name: trackaccess
description: TrackAccess Library Attendance System
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.2
  file_picker: ^8.0.0
  sqflite_common_ffi: ^2.3.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_libserialport: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png